[build]
  command = "npm run build"
  publish = "backend"  # Ensure this points to where your build artifacts are located

[functions]
  directory = "backend/functions"  # Ensure this points to where your functions are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
